front/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'front'
urlpatterns = [
                  path('', views.show, name='show'),
                  path('show_model/', views.show_model, name='show_model'),
                  path('reduce_fogy/', views.reduce_fogy, name='reduce_fogy'),
                  path('seam_carving/', views.seam_carving, name='seam_carving'),
                  path('sift/', views.sift, name='sift'),
                  path('filter/', views.flr_set, name='filter'),
                  path('route/', views.al_route, name='route'),
                  path('route_alo/', views.al_route_alo, name='route_alo'),
                  path('BP/', views.BP, name='BP'),
                  path('add_pay/', views.android_pay, name='add_pay'),
                  path('add_pay_web/', views.add_pay_web, name='add_pay_web'),
                  path('show_pay_web/', views.show_pay_web, name='show_pay_web'),
                  path('android_login_api/', views.android_login_api, name='android_login_api'),
                  path('android_register_api/', views.android_register_api, name='android_register_api'),
                  path('android_get_password_back/', views.android_get_password_back, name='android_get_password_back'),
                  path('android_get_password_back_db_operation/', views.android_get_password_back_db_operation, name='android_get_password_back_db_operation'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

media_homeworks/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('front.urls')),
    # path('admin/', admin.site.urls),
]

templates/SeamCarving.html
{% extends 'index.html' %}
{% block title %}SeamCarving{% endblock %}
{% block content %}
    {% if message %}
        <div class="alert alert-primary alert-dismissible fade show mb-0" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <i class="fa fa-check mx-2"></i>
            <strong>{{ message }}</strong>
        </div>
    {% endif %}

    <div class="main-content-container container-fluid px-4">
        <!-- Page Header -->
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
                <span class="text-uppercase page-subtitle">Overview</span>
                <h3 class="page-title">SeamCarving</h3>
            </div>
        </div>
        <!-- End Page Header -->
        <!-- Default Light Table -->
        <div class="row">
            <div class="col-lg-4">
                <div class="card card-small mb-4 pt-3">
                    <div class="card-header border-bottom text-center">
                        <h4 class="mb-0">操作板</h4>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item px-4">
                            <div class="progress-wrapper">
                                <strong class="text-muted d-block mb-2">传入图片</strong>
                                <form class='' action="{% url 'front:seam_carving' %}" method="post"
                                      enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <span>{{ image.image }}
                                        <button type="submit" class="btn btn-pill btn-outline-primary">start
                                        </button>
                                    </span>
                                    <input min="1" max="100" name="range" type="range"
                                           style="width: 100%">
                                </form>
                            </div>


                        </li>
                        <li class="list-group-item p-4">
                            <strong class="text-muted d-block mb-2">Description</strong>
                            <span>使用默认图片裁剪50% 用时约30s，拖动滑条，点击开始</span>
                        </li>

                    </ul>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card card-small mb-4">
                    <div class="card-header border-bottom">
                        <h6 class="m-0">original_picture</h6>
                    </div>
                    <div align="center">
                        {% if img_ob %}
                            -><img src="{{ img_ob.image.url }}" width="auto"
                                   height="auto"><-
                        {% elif img_ob_after %}
                            -><img src="{{ img_ob_after.image.url }}" width="auto"
                                   height="auto"><-
                        {% endif %}
                    </div>
                    <div class="card-header border-bottom">
                        <h6 class="m-0">processed_picture</h6>
                    </div>
                    <div align="center">
                        {% if img_ob %}
                            -><img src="{{ img_ob.image_processed.url }}" width="auto"
                                   height="auto"><-
                        {% elif img_ob_after %}
                            -><img src="{{ img_ob_after.image_processed.url }}" width="auto"
                                   height="auto"><-
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <!-- End Default Light Table -->
    </div>
{% endblock %}

templates/add_pay_web.html
{% extends 'index.html' %}
{% block title %}BP算法{% endblock %}
{% block content %}
    {% if message %}
        <div class="alert alert-primary alert-dismissible fade show mb-0" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <i class="fa fa-check mx-2"></i>
            <strong>{{ message }}</strong>
        </div>
    {% endif %}

    <div class="main-content-container container-fluid px-4">
        <!-- Page Header -->
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
                <span class="text-uppercase page-subtitle">Overview</span>
                <h3 class="page-title">{% block index %}添加消费{% endblock %}</h3>
            </div>
        </div>
        <!-- End Page Header -->
        <!-- Default Light Table -->
        <div class="col-lg-9 mb-6 offset-lg-1">
            <div class="card card-small mb-4">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item p-4">
                        <div class="row">
                            <div class="col-lg-12 mb-4 ">
                                <strong class="text-muted d-block mb-2">Forms</strong>
                                <form class='' action="{% url 'front:add_pay_web' %}" method="post">
                                        {% csrf_token %}
                                    <div class="form-group">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text" id="basic-addon1">项目</span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="items" name="items"
                                                   aria-label="items" aria-describedby="basic-addon1"></div>
                                    </div>
                                    <div class="form-group">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text" id="basic-addon1">花费</span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="123" name="cost"
                                                   aria-label="cost" aria-describedby="basic-addon1"></div>
                                    </div>
                                    <div class="form-group">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text" id="basic-addon1">日期</span>
                                            </div>
                                            <input type="date" class="form-control" placeholder="" name="date"
                                                   aria-label="cost" aria-describedby="basic-addon1"></div>
                                    </div>
                                    <div class="form-group">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text" id="basic-addon1">隐私</span>
                                            </div>
                                            <select id="inputState" class="form-control" name="isPri">
                                                <option selected>private</option>
                                                <option>public</option>
                                            </select>
                                        </div>
                                    </div>
                                    <input type="submit" class="btn btn-pill btn-outline-primary"
                                                        style="margin-top: auto">
                                </form>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

        <!-- End Default Light Table -->
    </div>
{% endblock %}

templates/fliter.html
{% extends 'index.html' %}
{% block title %}滤波{% endblock %}
{% block content %}
    {% if message %}
        <div class="alert alert-primary alert-dismissible fade show mb-0" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <i class="fa fa-check mx-2"></i>
            <strong>{{ message }}</strong>
        </div>
    {% endif %}

    <div class="main-content-container container-fluid px-4">
        <!-- Page Header -->
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
                <span class="text-uppercase page-subtitle">Overview</span>
                <h3 class="page-title">滤波</h3>
            </div>
        </div>
        <!-- End Page Header -->
        <!-- Default Light Table -->
        <div class="row">
            <div class="col-lg-4">
                <div class="card card-small mb-4 pt-3">
                    <div class="card-header border-bottom text-center">
                        <h4 class="mb-0">操作板</h4>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item px-4">
                            <div class="progress-wrapper">
                                <strong class="text-muted d-block mb-2">传入图片</strong>
                                <form class='' action="{% url 'front:filter' %}" method="post"
                                      enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div style="width: 100%">
                                        <span>{{ new_image.image }}</span></div>
                                    <span>
                                        <button type="submit" class="btn btn-pill btn-outline-primary"
                                                name="Gus">高斯</button>
                                        <button type="submit" class="btn btn-pill btn-outline-primary"
                                                name="avg">均值
                                        </button>
                                        <button type="submit" class="btn btn-pill btn-outline-primary"
                                                name="rec">方框
                                        </button>
                                        <button type="submit" class="btn btn-pill btn-outline-primary"
                                                name="rev">翻转
                                        </button>
                                        <button type="submit" class="btn btn-pill btn-outline-primary"
                                                name="rod">腐蚀
                                        </button>
                                        <button type="submit" class="btn btn-pill btn-outline-primary"
                                                name="add">膨胀
                                        </button>
                                    </span>
                                </form>
                            </div>


                        </li>
                        <li class="list-group-item p-4">
                            <strong class="text-muted d-block mb-2">Description</strong>
                            <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio eaque, quidem, commodi soluta qui quae minima obcaecati quod dolorum sint alias, possimus illum assumenda eligendi cumque?</span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card card-small mb-4">
                    <div class="card-header border-bottom">
                        <h6 class="m-0">original_picture</h6>
                    </div>
                    <div align="center">-><img src="{{ img_ob.image.url }}" width="auto"
                                               height="auto"><-
                    </div>
                    <div class="card-header border-bottom">
                        <h6 class="m-0">processed_picture</h6>
                    </div>
                    <div align="center">-><img src="{{ img_ob.image_processed.url }}" width="auto"
                                               height="auto"><-
                    </div>
                </div>
            </div>
        </div>
        <!-- End Default Light Table -->
    </div>
{% endblock %}

templates/fogy.html
{% extends 'index.html' %}
{% block title %}暗通道先验去雾{% endblock %}
{% block content %}
    {% if message %}
        <div class="alert alert-primary alert-dismissible fade show mb-0" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <i class="fa fa-check mx-2"></i>
            <strong>{{ message }}</strong>
        </div>
    {% endif %}

    <div class="main-content-container container-fluid px-4">
        <!-- Page Header -->
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
                <span class="text-uppercase page-subtitle">Overview</span>
                <h3 class="page-title">暗通道先验去雾</h3>
            </div>
        </div>
        <!-- End Page Header -->
        <!-- Default Light Table -->
        <div class="row">
            <div class="col-lg-4">
                <div class="card card-small mb-4 pt-3">
                    <div class="card-header border-bottom text-center">
                        <h4 class="mb-0">操作板</h4>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item px-4">
                            <div class="progress-wrapper">
                                <strong class="text-muted d-block mb-2">传入图片</strong>
                                <form class='' action="{% url 'front:reduce_fogy' %}" method="post"
                                      enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <span>{{ image.image }}
                                        <button type="submit" class="btn btn-pill btn-outline-primary">start
                                        </button>
                                    </span>
                                </form>
                            </div>


                        </li>
                        <li class="list-group-item p-4">
                            <strong class="text-muted d-block mb-2">Description</strong>
                            <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio eaque, quidem, commodi soluta qui quae minima obcaecati quod dolorum sint alias, possimus illum assumenda eligendi cumque?</span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card card-small mb-4">
                    <div class="card-header border-bottom">
                        <h6 class="m-0">original_picture</h6>
                    </div>
                    <div align="center">-><img src="{{ img_ob.image.url }}" width="auto"
                                                             height="auto"><-</div>
                    <div class="card-header border-bottom">
                        <h6 class="m-0">processed_picture</h6>
                    </div>
                    <div align="center">-><img src="{{ img_ob.image_processed.url }}" width="auto"
                                                             height="auto"><-</div>
                </div>
            </div>
        </div>
        <!-- End Default Light Table -->
    </div>
{% endblock %}

templates/route.html
{% extends 'index.html' %}
{% block title %}最短路径问题{% endblock %}
{% block content %}
    {% if message %}
        <div class="alert alert-primary alert-dismissible fade show mb-0" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <i class="fa fa-check mx-2"></i>
            <strong>{{ message }}</strong>
        </div>
    {% endif %}

    <div class="main-content-container container-fluid px-4">
        <!-- Page Header -->
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
                <span class="text-uppercase page-subtitle">Overview</span>
                <h3 class="page-title">{% block index %}最短路径{% endblock %}</h3>
            </div>
        </div>
        <!-- End Page Header -->
        <!-- Default Light Table -->
        <div class="row">
            <div class="col-lg-9">
                <div class="card card-small mb-4">
                    <div class="card-header border-bottom">
                        <h6 class="m-0">{% block sim %}生成图{% endblock %}</h6>
                    </div>
                    <div align="center"><img src="../media/image/test_board1.png" width="100%"
                                             height="auto">
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="card card-small mb-4 pt-3">
                    <div class="card-header border-bottom text-center">
                        <h4 class="mb-0">操作板</h4>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item px-4">
                            <div class="progress-wrapper">
                                {% block controlpanel %}
                                    <form class='' action="{% url 'front:route' %}" method="post"
                                          enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="form-row">
                                            <div class="form-group col-md-7">
                                                <select id="inputState" class="form-control" name="point_number">
                                                    <option selected>选择顶点数</option>
                                                    <option>10</option>
                                                    <option>15</option>
                                                    <option>20</option>
                                                    <option>25</option>
                                                    <option>30</option>
                                                    <option>35</option>
                                                    <option>40</option>
                                                    <option>45</option>
                                                    <option>50</option>
                                                </select>
                                            </div>
                                            <div class="form-group col-md-5">
                                                <button type="submit" class="btn btn-pill btn-outline-primary"
                                                        name="point">顶点生成
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                {% endblock %}
                            </div>


                        </li>
                        <li class="list-group-item p-4">
                            <strong class="text-muted d-block mb-2">Description</strong>
                            <span></span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- End Default Light Table -->
    </div>
{% endblock %}

templates/route_algorithms.html
{% extends 'index.html' %}
{% block title %}最短路径问题{% endblock %}
{% block content %}
    {% if message %}
        <div class="alert alert-primary alert-dismissible fade show mb-0" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <i class="fa fa-check mx-2"></i>
            <strong>{{ message }}</strong>
        </div>
    {% endif %}

    <div class="main-content-container container-fluid px-4">
        <!-- Page Header -->
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
                <span class="text-uppercase page-subtitle">Overview</span>
                <h3 class="page-title">最短路径</h3>
            </div>
        </div>
        <!-- End Page Header -->
        <!-- Default Light Table -->
        <div class="row">
            <div class="col-lg-9">
                <div class="card card-small mb-4">
                    <div class="card-header border-bottom">
                        <h6 class="m-0">生成图</h6>
                    </div>
                    <div align="center"><img src="{{ img_ob.image_add_points.url }}" width="auto"
                                             height="auto">
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="card card-small mb-4 pt-3">
                    <div class="card-header border-bottom text-center">
                        <h4 class="mb-0">操作板</h4>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item px-4">
                            <div class="progress-wrapper">
                                <strong class="text-muted d-block mb-2">功能选择</strong>
                                <form class='' action="{% url 'front:route_alo' %}" method="post"
                                      enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <div class="form-group col-md-9">
                                            <select id="inputState" class="form-control" name="point_number">
                                                <option selected>选择起点</option>
                                                {% for foo in x %}
                                                    <option>{{ forloop.counter }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div class="form-group col-md-9">
                                            <select id="inputState" class="form-control" name="point_number">
                                                <option selected>选择终点</option>
                                                {% for foo in x %}
                                                    <option>{{ forloop.counter }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div class="form-group col-md-5">
                                            <button type="submit" class="btn btn-pill btn-outline-primary"
                                                    style="margin-top: auto"
                                                    name="point">深度优先最短路径
                                            </button>
                                        </div>
                                        <div class="form-group col-md-5">
                                            <button type="submit" class="btn btn-pill btn-outline-primary"
                                                    style="margin-top: auto"
                                                    name="point">宽度优先最短路径
                                            </button>
                                        </div>
                                        <div class="form-group col-md-5">
                                            <button type="submit" class="btn btn-pill btn-outline-primary"
                                                    style="margin-top: auto"
                                                    name="point">A*搜索遍历
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>


                        </li>
                        <li class="list-group-item p-4">
                            <strong class="text-muted d-block mb-2">Description</strong>
                            <span></span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- End Default Light Table -->
    </div>
{% endblock %}

templates/sift.html
{% extends 'index.html' %}
{% block title %}sift{% endblock %}
{% block content %}
    {% if message %}
        <div class="alert alert-primary alert-dismissible fade show mb-0" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <i class="fa fa-check mx-2"></i>
            <strong>{{ message }}</strong>
        </div>
    {% endif %}

    <div class="main-content-container container-fluid px-4">
        <!-- Page Header -->
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
                <span class="text-uppercase page-subtitle">Overview</span>
                <h3 class="page-title">Sift</h3>
            </div>
        </div>
        <!-- End Page Header -->
        <!-- Default Light Table -->
        <div class="row">
            <div class="col-lg-4">
                <div class="card card-small mb-4 pt-3">
                    <div class="card-header border-bottom text-center">
                        <h4 class="mb-0">操作板</h4>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item px-4">
                            <div class="progress-wrapper">
                                <strong class="text-muted d-block mb-2">传入图片</strong>
                                <form class='' action="{% url 'front:sift' %}" method="post"
                                      enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <span>{{ new_image.image1 }} {{ new_image.image2 }}
                                        <button type="submit" class="btn btn-pill btn-outline-primary">start
                                        </button>
                                    </span>
                                </form>
                            </div>


                        </li>
                        <li class="list-group-item p-4">
                            <strong class="text-muted d-block mb-2">Description</strong>
                            <span>xxx</span>
                        </li>

                    </ul>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card card-small mb-4">
                    <div class="card-header border-bottom">
                        <h6 class="m-0">original_pictures</h6>
                    </div>
                    <div align="center">
                        -><img src="{{ img_ob.image1.url }}" width="auto"
                               height="auto">
                        <img src="{{ img_ob.image2.url }}" width="auto"
                             height="auto"><-
                    </div>
                    <div class="card-header border-bottom">
                        <h6 class="m-0">processed_picture</h6>
                    </div>
                    <div align="center">-><img src="{{ img_ob.image_processed.url }}" width="auto"
                                               height="auto"><-
                    </div>
                </div>
            </div>
        </div>
        <!-- End Default Light Table -->
    </div>
{% endblock %}